/*
 * 「知性蓝调」设计系统 - Mock 数据
 * 色彩: 深海蓝导航 + 天空蓝交互色 + 暖灰内容底色
 * 用途: 课程发现页面的模拟数据
 */

export interface Course {
  id: number;
  title: string;
  coverUrl: string;
  category: string;
  type: "直播" | "录播" | "专栏";
  teacher: string;
  learners: number;
  price: number;
  originalPrice: number;
  isFree: boolean;
  isVip: boolean;
  createdAt: string;
  /** 优惠券信息 */
  coupon?: {
    label: string;       // 如 "领券减50" "新人专享"
    amount: number;      // 优惠金额
  };
  /** 限时折扣信息 */
  discount?: {
    label: string;       // 如 "限时6折" "今日特惠"
    endsAt: string;      // 截止时间 ISO string
    percent?: number;    // 折扣百分比，如 60 表示6折
  };
}

export const COVER_IMAGES = {
  emotion: "https://d2xsxph8kpxj0f.cloudfront.net/110778359/jJ8VD4MsjQ8YJb6CrXvwEn/course-cover-emotion-nm2h7f9rTqhVZUGScFedR9.webp",
  mindfulness: "https://d2xsxph8kpxj0f.cloudfront.net/110778359/jJ8VD4MsjQ8YJb6CrXvwEn/course-cover-mindfulness-759bhBh7MnyueYMgucWpNt.webp",
  child: "https://d2xsxph8kpxj0f.cloudfront.net/110778359/jJ8VD4MsjQ8YJb6CrXvwEn/course-cover-child-psychology-kWKhZjgLAHFKmS4aJuspEx.webp",
  cognitive: "https://d2xsxph8kpxj0f.cloudfront.net/110778359/jJ8VD4MsjQ8YJb6CrXvwEn/course-cover-cognitive-W5TCmNSJTHpaUiUkVJ2NeL.webp",
  workplace: "https://d2xsxph8kpxj0f.cloudfront.net/110778359/jJ8VD4MsjQ8YJb6CrXvwEn/course-cover-workplace-S3CZKDnwzdWcPkCDb44Vhi.webp",
};

const UNSPLASH_COVERS = [
  "https://images.unsplash.com/photo-1573497019940-1c28c88b4f3e?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1516302752625-fcc3c50ae61f?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1544027993-37dbfe43562a?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1491438590914-bc09fcaaf77a?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1517486808906-6ca8b3f04846?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1571019613454-1cb2f99b2d8b?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1506126613408-eca07ce68773?w=400&h=225&fit=crop",
  "https://images.unsplash.com/photo-1434030216411-0b793f4b4173?w=400&h=225&fit=crop",
];

export const categories = [
  "全部",
  "个人成长",
  "情绪管理",
  "职场心理",
  "家庭教育",
  "心理科普",
  "婚姻关系",
  "青少年心理",
  "心理咨询师",
  "正念冥想",
  "认知行为",
  "催眠治疗",
  "沙盘疗法",
  "绘画疗法",
  "团体辅导",
];

export const courseTypes = ["全部", "直播", "录播", "专栏"];

export const sortOptions = [
  { label: "综合", value: "comprehensive" },
  { label: "最新", value: "newest" },
  { label: "最热", value: "hottest" },
  { label: "价格", value: "price" },
];

function getCoverForIndex(i: number): string {
  const generated = [
    COVER_IMAGES.emotion,
    COVER_IMAGES.mindfulness,
    COVER_IMAGES.child,
    COVER_IMAGES.cognitive,
    COVER_IMAGES.workplace,
  ];
  if (i < 5) return generated[i];
  return UNSPLASH_COVERS[(i - 5) % UNSPLASH_COVERS.length];
}

export const courses: Course[] = [
  {
    id: 1,
    title: "情绪管理入门：掌控你的情绪，提升生活品质",
    coverUrl: getCoverForIndex(0),
    category: "情绪管理",
    type: "录播",
    teacher: "李静博士",
    learners: 18890,
    price: 199,
    originalPrice: 399,
    isFree: false,
    isVip: true,
    createdAt: "2026-03-01",
    discount: {
      label: "限时5折",
      endsAt: "2026-03-20T23:59:59",
      percent: 50,
    },
  },
  {
    id: 2,
    title: "正念减压疗法 (MBSR) 八周系统训练营",
    coverUrl: getCoverForIndex(1),
    category: "正念冥想",
    type: "直播",
    teacher: "王宇教授",
    learners: 7562,
    price: 998,
    originalPrice: 1299,
    isFree: false,
    isVip: false,
    createdAt: "2026-02-28",
    coupon: {
      label: "领券减100",
      amount: 100,
    },
  },
  {
    id: 3,
    title: "认识抑郁：科学走出情绪阴霾的第一课",
    coverUrl: getCoverForIndex(2),
    category: "心理科普",
    type: "录播",
    teacher: "赵磊咨询师",
    learners: 35241,
    price: 0,
    originalPrice: 0,
    isFree: true,
    isVip: false,
    createdAt: "2026-02-25",
  },
  {
    id: 4,
    title: "儿童积极心理学：培养拥有幸福感和复原力的孩子",
    coverUrl: getCoverForIndex(3),
    category: "家庭教育",
    type: "专栏",
    teacher: "孙悦博士",
    learners: 12054,
    price: 249,
    originalPrice: 499,
    isFree: false,
    isVip: true,
    createdAt: "2026-02-20",
    discount: {
      label: "今日特惠",
      endsAt: "2026-03-15T23:59:59",
      percent: 50,
    },
    coupon: {
      label: "新人专享减30",
      amount: 30,
    },
  },
  {
    id: 5,
    title: "职场压力管理与高效能人士的心理韧性训练",
    coverUrl: getCoverForIndex(4),
    category: "职场心理",
    type: "直播",
    teacher: "陈明教授",
    learners: 9823,
    price: 599,
    originalPrice: 899,
    isFree: false,
    isVip: false,
    createdAt: "2026-02-18",
    coupon: {
      label: "领券减80",
      amount: 80,
    },
  },
  {
    id: 6,
    title: "亲密关系心理学：建立健康的婚姻与伴侣关系",
    coverUrl: getCoverForIndex(5),
    category: "婚姻关系",
    type: "录播",
    teacher: "刘芳博士",
    learners: 15678,
    price: 299,
    originalPrice: 599,
    isFree: false,
    isVip: true,
    createdAt: "2026-02-15",
    discount: {
      label: "限时6折",
      endsAt: "2026-03-18T23:59:59",
      percent: 60,
    },
  },
  {
    id: 7,
    title: "青少年心理健康指南：家长必修课",
    coverUrl: getCoverForIndex(6),
    category: "青少年心理",
    type: "直播",
    teacher: "张伟教授",
    learners: 8934,
    price: 0,
    originalPrice: 0,
    isFree: true,
    isVip: false,
    createdAt: "2026-02-12",
  },
  {
    id: 8,
    title: "认知行为疗法 (CBT) 系统学习：从理论到实践",
    coverUrl: getCoverForIndex(7),
    category: "认知行为",
    type: "专栏",
    teacher: "周强博士",
    learners: 6721,
    price: 1299,
    originalPrice: 1999,
    isFree: false,
    isVip: true,
    createdAt: "2026-02-10",
    coupon: {
      label: "领券减200",
      amount: 200,
    },
  },
  {
    id: 9,
    title: "心理咨询师成长之路：从入门到执业",
    coverUrl: getCoverForIndex(8),
    category: "心理咨询师",
    type: "录播",
    teacher: "吴丽教授",
    learners: 11234,
    price: 1599,
    originalPrice: 2499,
    isFree: false,
    isVip: false,
    createdAt: "2026-02-08",
    discount: {
      label: "限时特价",
      endsAt: "2026-03-22T23:59:59",
      percent: 64,
    },
    coupon: {
      label: "领券减150",
      amount: 150,
    },
  },
  {
    id: 10,
    title: "每日十分钟正念冥想：缓解焦虑与失眠",
    coverUrl: getCoverForIndex(9),
    category: "正念冥想",
    type: "录播",
    teacher: "林雪老师",
    learners: 28976,
    price: 0,
    originalPrice: 0,
    isFree: true,
    isVip: false,
    createdAt: "2026-02-05",
  },
  {
    id: 11,
    title: "个人成长心理学：发现你的内在力量",
    coverUrl: getCoverForIndex(10),
    category: "个人成长",
    type: "直播",
    teacher: "黄强博士",
    learners: 14567,
    price: 399,
    originalPrice: 699,
    isFree: false,
    isVip: false,
    createdAt: "2026-02-03",
    discount: {
      label: "限时4.3折",
      endsAt: "2026-03-16T23:59:59",
      percent: 43,
    },
  },
  {
    id: 12,
    title: "催眠治疗入门：探索潜意识的奥秘",
    coverUrl: getCoverForIndex(11),
    category: "催眠治疗",
    type: "专栏",
    teacher: "郑华教授",
    learners: 5432,
    price: 799,
    originalPrice: 1199,
    isFree: false,
    isVip: true,
    createdAt: "2026-01-30",
  },
  {
    id: 13,
    title: "沙盘疗法实操：儿童心理治疗的艺术",
    coverUrl: getCoverForIndex(12),
    category: "沙盘疗法",
    type: "直播",
    teacher: "马丽博士",
    learners: 3876,
    price: 899,
    originalPrice: 1399,
    isFree: false,
    isVip: false,
    createdAt: "2026-01-28",
  },
  {
    id: 14,
    title: "绘画疗法工作坊：用色彩表达内心世界",
    coverUrl: getCoverForIndex(13),
    category: "绘画疗法",
    type: "录播",
    teacher: "许静老师",
    learners: 4523,
    price: 0,
    originalPrice: 0,
    isFree: true,
    isVip: false,
    createdAt: "2026-01-25",
  },
  {
    id: 15,
    title: "团体心理辅导技术：从设计到实施",
    coverUrl: getCoverForIndex(14),
    category: "团体辅导",
    type: "直播",
    teacher: "杨光教授",
    learners: 2987,
    price: 1099,
    originalPrice: 1699,
    isFree: false,
    isVip: true,
    createdAt: "2026-01-22",
  },
  {
    id: 16,
    title: "情绪急救手册：应对生活中的突发心理危机",
    coverUrl: getCoverForIndex(15),
    category: "情绪管理",
    type: "录播",
    teacher: "李静博士",
    learners: 21345,
    price: 149,
    originalPrice: 299,
    isFree: false,
    isVip: false,
    createdAt: "2026-01-20",
    coupon: {
      label: "新人专享减20",
      amount: 20,
    },
  },
  {
    id: 17,
    title: "职场沟通心理学：高情商表达的秘密",
    coverUrl: getCoverForIndex(0),
    category: "职场心理",
    type: "专栏",
    teacher: "陈明教授",
    learners: 17654,
    price: 399,
    originalPrice: 699,
    isFree: false,
    isVip: true,
    createdAt: "2026-01-18",
    discount: {
      label: "限时4.3折",
      endsAt: "2026-03-19T23:59:59",
      percent: 43,
    },
    coupon: {
      label: "领券减50",
      amount: 50,
    },
  },
  {
    id: 18,
    title: "家庭系统排列：理解家庭动力与代际传承",
    coverUrl: getCoverForIndex(1),
    category: "家庭教育",
    type: "直播",
    teacher: "刘芳博士",
    learners: 6543,
    price: 699,
    originalPrice: 999,
    isFree: false,
    isVip: false,
    createdAt: "2026-01-15",
  },
  {
    id: 19,
    title: "心理学与日常生活：有趣的心理学效应解读",
    coverUrl: getCoverForIndex(2),
    category: "心理科普",
    type: "录播",
    teacher: "赵磊咨询师",
    learners: 42567,
    price: 0,
    originalPrice: 0,
    isFree: true,
    isVip: false,
    createdAt: "2026-01-12",
  },
  {
    id: 20,
    title: "婚姻中的情感修复：从冲突到和解的心理路径",
    coverUrl: getCoverForIndex(3),
    category: "婚姻关系",
    type: "录播",
    teacher: "张伟教授",
    learners: 8765,
    price: 499,
    originalPrice: 799,
    isFree: false,
    isVip: false,
    createdAt: "2026-01-10",
  },
  {
    id: 21,
    title: "高敏感人群的自我关怀与能量管理",
    coverUrl: getCoverForIndex(4),
    category: "个人成长",
    type: "录播",
    teacher: "林雪老师",
    learners: 13245,
    price: 259,
    originalPrice: 459,
    isFree: false,
    isVip: true,
    createdAt: "2026-01-08",
  },
  {
    id: 22,
    title: "焦虑症的认知行为干预：实用技术与案例分析",
    coverUrl: getCoverForIndex(5),
    category: "认知行为",
    type: "直播",
    teacher: "周强博士",
    learners: 7890,
    price: 899,
    originalPrice: 1399,
    isFree: false,
    isVip: false,
    createdAt: "2026-01-05",
  },
  {
    id: 23,
    title: "青少年网络成瘾的心理干预策略",
    coverUrl: getCoverForIndex(6),
    category: "青少年心理",
    type: "专栏",
    teacher: "马丽博士",
    learners: 5678,
    price: 599,
    originalPrice: 899,
    isFree: false,
    isVip: false,
    createdAt: "2026-01-03",
  },
  {
    id: 24,
    title: "心理咨询伦理与职业规范：执业必备知识",
    coverUrl: getCoverForIndex(7),
    category: "心理咨询师",
    type: "录播",
    teacher: "吴丽教授",
    learners: 4321,
    price: 0,
    originalPrice: 0,
    isFree: true,
    isVip: false,
    createdAt: "2026-01-01",
  },
];

export const PAGE_SIZE = 12;
