export type DatabaseDomain =
  | "auth"
  | "commerce"
  | "assessment"
  | "counseling"
  | "risk"
  | "audit";

export type CoreDatabaseTable = {
  name: string;
  domain: DatabaseDomain;
  purpose: string;
  requiredColumns: readonly string[];
};

export const coreDatabaseTables = [
  {
    name: "users",
    domain: "auth",
    purpose: "Stable user profile and privacy-minimized identity fields.",
    requiredColumns: [
      "id",
      "display_name",
      "phone_masked",
      "avatar_url",
      "is_minor",
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "user_roles",
    domain: "auth",
    purpose: "RBAC role assignments kept separate from the user profile.",
    requiredColumns: ["user_id", "role", "created_at"],
  },
  {
    name: "user_consents",
    domain: "auth",
    purpose: "Terms and privacy consent audit trail by version.",
    requiredColumns: ["user_id", "type", "version", "accepted_at"],
  },
  {
    name: "auth_sessions",
    domain: "auth",
    purpose: "Server-side session metadata and token hashes.",
    requiredColumns: [
      "id",
      "user_id",
      "provider",
      "token_hash",
      "expires_at",
      "revoked_at",
      "created_at",
    ],
  },
  {
    name: "course_memberships",
    domain: "commerce",
    purpose: "Course membership entitlement snapshot per user.",
    requiredColumns: [
      "user_id",
      "status",
      "plan_name",
      "activated_at",
      "expires_at",
      "source_type",
      "source_order_id",
      "source_actor_id",
      "source_updated_at",
      "updated_at",
    ],
  },
  {
    name: "course_access_grants",
    domain: "commerce",
    purpose: "Owned course grants derived from purchase or manual operations.",
    requiredColumns: [
      "id",
      "user_id",
      "course_id",
      "source_order_id",
      "granted_at",
      "revoked_at",
    ],
  },
  {
    name: "orders",
    domain: "commerce",
    purpose: "Payable order header for courses, memberships and counseling.",
    requiredColumns: [
      "id",
      "user_id",
      "status",
      "subtotal_cents",
      "discount_cents",
      "payable_cents",
      "created_at",
      "paid_at",
    ],
  },
  {
    name: "order_items",
    domain: "commerce",
    purpose: "Order line items mapped from shared OrderItem.",
    requiredColumns: [
      "id",
      "order_id",
      "type",
      "target_id",
      "title",
      "unit_price_cents",
      "quantity",
      "created_at",
    ],
  },
  {
    name: "payments",
    domain: "commerce",
    purpose: "Payment attempts and provider transaction ids.",
    requiredColumns: [
      "id",
      "order_id",
      "channel",
      "amount_cents",
      "transaction_id",
      "paid_at",
      "created_at",
    ],
  },
  {
    name: "payment_webhook_events",
    domain: "commerce",
    purpose: "Idempotent payment provider webhook receipt and response log.",
    requiredColumns: [
      "id",
      "event_type",
      "order_id",
      "channel",
      "status",
      "event_payload",
      "response_status",
      "response_body",
      "error_message",
      "received_at",
      "processed_at",
      "updated_at",
    ],
  },
  {
    name: "course_products",
    domain: "commerce",
    purpose: "Operational course product catalog for public course publishing.",
    requiredColumns: [
      "id",
      "course_id",
      "title",
      "cover_url",
      "category",
      "type",
      "instructor_name",
      "learners",
      "amount_cents",
      "original_amount_cents",
      "is_free",
      "member_included",
      "status",
      "review_status",
      "source",
      "created_at",
      "updated_at",
      "published_at",
    ],
  },
  {
    name: "course_product_contents",
    domain: "commerce",
    purpose:
      "Operational course product detail content, chapters and material placeholders.",
    requiredColumns: [
      "product_id",
      "summary",
      "target_audience",
      "sales_assets",
      "chapters",
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "course_product_asset_objects",
    domain: "commerce",
    purpose:
      "Object storage facts for course product assets, including provider, key and content hash.",
    requiredColumns: [
      "object_key",
      "provider",
      "bucket",
      "region",
      "mime_type",
      "size_bytes",
      "content_hash",
      "original_file_name",
      "reference_count",
      "created_by",
      "created_at",
      "deleted_at",
    ],
  },
  {
    name: "course_product_assets",
    domain: "commerce",
    purpose:
      "Operational course product asset metadata with compliance, download and soft-delete state.",
    requiredColumns: [
      "id",
      "product_id",
      "course_id",
      "chapter_id",
      "kind",
      "title",
      "file_name",
      "mime_type",
      "size_bytes",
      "source_type",
      "storage_key",
      "object_key",
      "content_hash",
      "public_url",
      "usage",
      "compliance_status",
      "download_enabled",
      "reference_count",
      "uploaded_by",
      "uploaded_at",
      "reviewed_by",
      "reviewed_at",
      "deleted_at",
      "updated_at",
    ],
  },
  {
    name: "course_product_asset_references",
    domain: "commerce",
    purpose:
      "Course asset references from merchandising blocks and chapter material placeholders.",
    requiredColumns: [
      "id",
      "asset_id",
      "product_id",
      "course_id",
      "chapter_id",
      "reference_type",
      "material_placeholder_id",
      "material_placeholder_index",
      "created_by",
      "created_at",
      "deleted_at",
    ],
  },
  {
    name: "course_product_audit_events",
    domain: "audit",
    purpose:
      "Append-only audit events for course product operations and review workflow.",
    requiredColumns: [
      "id",
      "product_id",
      "product_title",
      "actor_id",
      "action",
      "reason",
      "before_payload",
      "after_payload",
      "created_at",
    ],
  },
  {
    name: "user_membership_audit_events",
    domain: "audit",
    purpose:
      "Append-only audit events for manual user membership entitlement operations.",
    requiredColumns: [
      "id",
      "user_id",
      "actor_id",
      "actor_roles",
      "action",
      "reason",
      "before_membership",
      "after_membership",
      "created_at",
    ],
  },
  {
    name: "order_admin_exception_flags",
    domain: "audit",
    purpose:
      "Current order exception marker for operations triage, backed by audit events.",
    requiredColumns: [
      "order_id",
      "status",
      "severity",
      "reason",
      "marked_by",
      "marked_at",
      "cleared_by",
      "cleared_at",
    ],
  },
  {
    name: "order_admin_audit_events",
    domain: "audit",
    purpose:
      "Append-only audit events for manual order operations and exception workflow.",
    requiredColumns: [
      "id",
      "order_id",
      "user_id",
      "actor_id",
      "actor_roles",
      "action",
      "reason",
      "before_snapshot",
      "after_snapshot",
      "created_at",
    ],
  },
  {
    name: "transaction_admin_work_orders",
    domain: "audit",
    purpose:
      "Current transaction exception work order for payment and refund triage.",
    requiredColumns: [
      "id",
      "transaction_id",
      "order_id",
      "status",
      "severity",
      "reason",
      "marked_by",
      "marked_at",
      "resolved_by",
      "resolved_at",
      "resolution",
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "transaction_admin_audit_events",
    domain: "audit",
    purpose:
      "Append-only audit events for transaction refund and exception workflows.",
    requiredColumns: [
      "id",
      "transaction_id",
      "order_id",
      "user_id",
      "actor_id",
      "actor_roles",
      "action",
      "reason",
      "before_snapshot",
      "after_snapshot",
      "refund_provider_result",
      "created_at",
    ],
  },
  {
    name: "assessment_reports",
    domain: "assessment",
    purpose: "Generated assessment report, scores and recommendations.",
    requiredColumns: [
      "id",
      "user_id",
      "flow_id",
      "dimensions",
      "risk_level",
      "summary",
      "recommendations",
      "risk_event_id",
      "created_at",
    ],
  },
  {
    name: "counselors",
    domain: "counseling",
    purpose: "Counselor public profile and service pricing metadata.",
    requiredColumns: [
      "id",
      "name",
      "avatar_url",
      "title",
      "introduction",
      "specialties",
      "license_summary",
      "years_of_practice",
      "session_price_cents",
      "rating",
      "status",
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "counseling_slots",
    domain: "counseling",
    purpose: "Bookable counselor time slots.",
    requiredColumns: [
      "id",
      "counselor_id",
      "starts_at",
      "ends_at",
      "channel",
      "available",
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "counseling_appointments",
    domain: "counseling",
    purpose: "User counseling appointment and intake metadata.",
    requiredColumns: [
      "id",
      "user_id",
      "counselor_id",
      "slot_id",
      "order_id",
      "channel",
      "status",
      "concern_tags",
      "note_for_counselor",
      "assessment_report_id",
      "risk_event_id",
      "created_at",
      "updated_at",
    ],
  },
  {
    name: "counseling_operation_settings",
    domain: "counseling",
    purpose: "Versioned operational settings for counseling workflows.",
    requiredColumns: ["key", "value", "updated_by", "created_at", "updated_at"],
  },
  {
    name: "counseling_operation_audit_events",
    domain: "audit",
    purpose: "Counseling-specific policy and fulfillment audit events.",
    requiredColumns: [
      "id",
      "action",
      "actor_id",
      "actor_roles",
      "appointment_id",
      "user_id",
      "counselor_id",
      "previous_appointment_status",
      "next_appointment_status",
      "previous_order_status",
      "next_order_status",
      "policy_before",
      "policy_after",
      "note",
      "created_at",
    ],
  },
  {
    name: "risk_events",
    domain: "risk",
    purpose:
      "Open, reviewed and resolved risk events from assessment or intake.",
    requiredColumns: [
      "id",
      "user_id",
      "source",
      "risk_level",
      "signal",
      "status",
      "reviewer_id",
      "created_at",
      "resolved_at",
    ],
  },
  {
    name: "risk_admin_review_records",
    domain: "audit",
    purpose:
      "Append-only risk review handling records with audit-center projection fields.",
    requiredColumns: [
      "id",
      "risk_event_id",
      "user_id",
      "action",
      "actor_id",
      "actor_roles",
      "previous_status",
      "next_status",
      "note",
      "sop_template_id",
      "sop_template_version",
      "result_template_id",
      "escalation_snapshot",
      "audit_resource_type",
      "audit_resource_id",
      "before_snapshot",
      "after_snapshot",
      "created_at",
    ],
  },
  {
    name: "risk_sop_templates",
    domain: "risk",
    purpose:
      "Versioned risk SOP templates matched by risk level and event source.",
    requiredColumns: [
      "id",
      "title",
      "version",
      "enabled",
      "risk_levels",
      "sources",
      "owner_role",
      "steps",
      "result_templates",
      "updated_at",
      "audit_resource_type",
      "audit_resource_id",
      "last_actor_id",
      "last_actor_roles",
      "last_action",
      "last_reason",
      "before_snapshot",
      "after_snapshot",
      "audit_updated_at",
    ],
  },
  {
    name: "risk_escalation_queue_items",
    domain: "risk",
    purpose:
      "Current risk escalation queue item per risk event for operations triage.",
    requiredColumns: [
      "id",
      "risk_event_id",
      "user_id",
      "priority",
      "status",
      "owner_id",
      "reason",
      "created_at",
      "resolved_at",
      "audit_resource_type",
      "audit_resource_id",
      "last_actor_id",
      "last_actor_roles",
      "last_action",
      "before_snapshot",
      "after_snapshot",
      "audit_updated_at",
    ],
  },
  {
    name: "audit_center_archived_events",
    domain: "audit",
    purpose:
      "Append-only normalized audit archive for cross-module search and long-term retention.",
    requiredColumns: [
      "id",
      "idempotency_key",
      "source_module",
      "source_event_id",
      "source_store",
      "source_table",
      "source_record_id",
      "module",
      "action",
      "resource_type",
      "resource_id",
      "resource_label",
      "actor_id",
      "actor_roles",
      "reason",
      "summary",
      "before_summary",
      "after_summary",
      "occurred_at",
      "archived_at",
      "schema_version",
      "policy_version",
      "privacy_level",
      "backfill_batch_id",
    ],
  },
  {
    name: "audit_logs",
    domain: "audit",
    purpose: "Append-only operational audit trail.",
    requiredColumns: [
      "id",
      "actor_id",
      "action",
      "resource_type",
      "resource_id",
      "ip",
      "user_agent",
      "created_at",
    ],
  },
] as const satisfies readonly CoreDatabaseTable[];

export const requiredDatabaseIndexes = [
  "idx_auth_sessions_user_id",
  "idx_course_access_grants_user_id",
  "idx_orders_user_id_created_at",
  "idx_payment_webhook_events_order_id",
  "idx_payment_webhook_events_status_received_at",
  "uniq_course_products_course_id",
  "idx_course_products_status_updated_at",
  "idx_course_products_review_status_updated_at",
  "idx_course_product_contents_updated_at",
  "idx_course_product_asset_objects_hash",
  "idx_course_product_asset_objects_created_at",
  "idx_course_product_asset_objects_deleted_at",
  "idx_course_product_assets_product_updated_at",
  "idx_course_product_assets_course_chapter",
  "idx_course_product_assets_compliance",
  "idx_course_product_assets_object_key",
  "idx_course_product_assets_active",
  "idx_course_product_asset_references_asset_active",
  "idx_course_product_asset_references_product_course",
  "idx_course_product_asset_references_type_created_at",
  "idx_course_product_audit_events_product_created_at",
  "idx_course_product_audit_events_created_at",
  "idx_user_membership_audit_events_user_created_at",
  "idx_user_membership_audit_events_actor_created_at",
  "idx_order_admin_exception_flags_status_marked_at",
  "idx_order_admin_audit_events_order_created_at",
  "idx_order_admin_audit_events_actor_created_at",
  "idx_transaction_admin_work_orders_status_marked_at",
  "idx_transaction_admin_work_orders_order_id",
  "idx_transaction_admin_audit_events_transaction_created_at",
  "idx_transaction_admin_audit_events_order_created_at",
  "idx_transaction_admin_audit_events_actor_created_at",
  "idx_assessment_reports_user_id_created_at",
  "idx_counseling_slots_counselor_starts_at",
  "idx_counseling_appointments_user_id_created_at",
  "idx_counseling_appointments_order_id",
  "idx_counseling_operation_audit_events_created_at",
  "idx_counseling_operation_audit_events_appointment",
  "idx_counseling_operation_audit_events_actor",
  "idx_risk_events_user_status",
  "idx_risk_admin_review_records_risk_event_created_at",
  "idx_risk_admin_review_records_actor_created_at",
  "idx_risk_admin_review_records_audit_resource",
  "idx_risk_sop_templates_enabled_updated_at",
  "idx_risk_sop_templates_audit_resource",
  "idx_risk_escalation_queue_status_priority_created_at",
  "idx_risk_escalation_queue_risk_event",
  "idx_risk_escalation_queue_audit_resource",
  "uniq_audit_center_archived_events_idempotency_key",
  "idx_audit_center_archived_events_module_occurred_at",
  "idx_audit_center_archived_events_action_occurred_at",
  "idx_audit_center_archived_events_resource",
  "idx_audit_center_archived_events_actor_occurred_at",
  "idx_audit_center_archived_events_source",
  "idx_audit_center_archived_events_archived_at",
  "idx_audit_logs_resource",
] as const;
